---
# tasks file for firewall rules configuration
- name: Configuring firewall rules for Red Hat Satellite
  firewalld:
    #service: "{{ item }}"
    port: "{{ item.port }}/{{ item.proto }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - { port: "80", proto: "tcp" }
    - { port: "443", proto: "tcp" }
    - { port: "5647", proto: "tcp" }
    - { port: "8000", proto: "tcp" }
    - { port: "8140", proto: "tcp" }
    - { port: "9090", proto: "tcp" }
    - { port: "53", proto: "tcp" }
    - { port: "53", proto: "udp" }
    - { port: "67", proto: "tcp" }
    - { port: "67", proto: "udp" }
