---
# tasks file for
- name: Install Red Hat Satellite package
  yum:
    name: satellite
    state: present

- name: Configure Red Hat Satellite
  command: |
    satellite-installer --scenario satellite
    --foreman-initial-organization {{ sat_organization }}
    --foreman-initial-location {{ sat_location }}
    --foreman-initial-admin-username {{ sat_username }}
    --foreman-initial-admin-password {{ sat_password }}
  register: installer
  changed_when: installer.rc != 0